# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: gh:radio-aktywne/template-database-postgres
accountname: radio-aktywne
databasename: graphite
description: Broadcast playlists data 💽
docs: true
docsurl: https://radio-aktywne.github.io/graphite
envprefix: GRAPHITE
imagename: databases/graphite
port: 10220
registry: true
releases: true
reponame: graphite
repourl: https://github.com/radio-aktywne/graphite
