# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:radio-aktywne/template-database-cockroach
accountname: radio-aktywne
databasename: graphite
description: Broadcast playlists data 💽
docs: true
docsurl: https://radio-aktywne.github.io/graphite
envprefix: GRAPHITE
httpport: 10221
imagename: databases/graphite
registry: true
releases: true
reponame: graphite
repourl: https://github.com/radio-aktywne/graphite
rpcport: 10222
sqlport: 10220
