services:
  graphite:
    build:
      context: ./
      network: host
    environment:
      - "GRAPHITE__SERVER__HOST=${GRAPHITE__SERVER__HOST:-0.0.0.0}"
      - "GRAPHITE__SERVER__PORT=${GRAPHITE__SERVER__PORT:-10220}"
      - "GRAPHITE__CREDENTIALS__USER__PASSWORD=${GRAPHITE__CREDENTIALS__USER__PASSWORD:-password}"
    network_mode: host
    volumes:
      - data:/database/data/

volumes:
  data: {}
