services:
  graphite:
    build:
      context: ./
      network: host
    environment:
      - "GRAPHITE__SERVER__HOST=${GRAPHITE__SERVER__HOST:-0.0.0.0}"
      - "GRAPHITE__SERVER__PORTS__SQL=${GRAPHITE__SERVER__PORTS__SQL:-41000}"
      - "GRAPHITE__SERVER__PORTS__HTTP=${GRAPHITE__SERVER__PORTS__HTTP:-41001}"
      - "GRAPHITE__SERVER__PORTS__RPC=${GRAPHITE__SERVER__PORTS__RPC:-41002}"
      - "GRAPHITE__CREDENTIALS__ROOT__PASSWORD=${GRAPHITE__CREDENTIALS__ROOT__PASSWORD:-password}"
      - "GRAPHITE__CREDENTIALS__USER__PASSWORD=${GRAPHITE__CREDENTIALS__USER__PASSWORD:-password}"
    network_mode: host
    privileged: true
    volumes:
      - data:/database/data/

volumes:
  data: {}
